---
server:
  port: 8140 
eureka:
  client:
    availability-zone: http://localhost:8761/eureka/
---
spring:
  profiles: default,local
  jpa.show-sql : true
  jpa.generate-ddl : true
  datasource:
   url : jdbc:postgresql://localhost:5432/db_transfers
   username : postgres
   password : admin
   driverClassName : org.postgresql.Driver
   testWhileIdle : true
   validationQuery : SELECT 1
max:
 recent:
  transactions : 10
---
spring:
  profiles: docker
  jpa.show-sql : true
  jpa.generate-ddl : true
  datasource:
   url : jdbc:postgresql://192.168.99.100:5432/db_transfers
   username : postgres
   password : admin
   driverClassName : org.postgresql.Driver
   testWhileIdle : true
   validationQuery : SELECT 1
max:
 recent:
  transactions : 10
